name: Deploy to Docker and EC2 with nginx

on:
  push:
    branches:
      - main  # 배포 트리거가 되는 브랜치를 지정합니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./mysite/requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mealkid:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mealkid:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/mealkid:cache,mode=max

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/mealkid
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mealkid:latest
          sudo docker-compose stop mealkid
          sudo docker-compose rm -f mealkid
          sudo docker-compose up -d mealkid
          sudo docker rmi $(sudo docker images -f "dangling=true" -q)
